### ISSUE TITLE
Named function instead of callback

### ISSUE THREAD

**Issue by jacobdubail** [avk/jQuery-Chrono#11]
Thanks for writing this plugin. setInterval always seems to bust my balls...

When I try to pass a named function, like this, I get an error:

$.every( 5000, rotate("tweets") );

Instead, I have to pass the entire function into the $.every call.  

Am I doing something wrong?  Or is this intended?

Thanks again!

-Jacob

**Comment by jacobdubail** [comment]
Oh yeah,

And how would clearTimeout work with this?

Thanks,
Jacob

**Comment by ai** [comment]
O_o

``` js
$.every( 5000, rotate("tweets") );
```

Will never work in JS. You need write:

``` js
$.every( 5000, function() { rotate("tweets") } );
```

or:

``` js
var rotateTweets = function () { rotate("tweets") };
$.every( 5000, rotateTweets );
```

**Comment by ai** [comment]
I think you need to close issue, because there is no way to realize it. When you write `func()` you execute `func` immedently and get function return.

**Comment by avk** [comment]
ai's last comment is correct. Closing.

**Comment by jacobdubail** [comment]
Any comment about clearTimeout, then?

**Comment by ai** [comment]
@jacobdubail, what about `clearTimeout`? `setTimeout` return ID and we put it as first argument to `clearTimeout`.

``` js
var id = setTimeout(function () { … }, 1000);
clearTimeout(id);
```

**Comment by jacobdubail** [comment]
perfect. thanks.
