### ISSUE TITLE
Why does this require jQuery?

### ISSUE THREAD

**Issue by jeremyckahn** [avk/jQuery-Chrono#6]
After a quick peek through the source, there are only a few calls to jQuery methods.  Requiring jQuery is a pretty significant dependency if all you need is `extend()` functionality and error logging.  Perhaps this tool would benefit from not requiring jQuery?

**Comment by Twipped** [comment]
That's precisely what [my fork](https://github.com/ChiperSoft/Timed) changes.

**Comment by jeremyckahn** [comment]
Nice.  I see that it's on microjs.com as well, well done sir!

**Comment by avk** [comment]
Thanks, been getting that question more often. Will make a jQuery-less version as well in the near future.

**Comment by jeremyckahn** [comment]
Sounds great.  I like the idea behind the library, I can see it being useful in a bunch of applications.

**Comment by avk** [comment]
Version 1.2 no longer requires jQuery! Thanks to ai's work on this: https://github.com/avk/jQuery-Chrono/pull/10
