### ISSUE TITLE
clearTimeout()?

### ISSUE THREAD

**Issue by mynameistechno** [avk/jQuery-Chrono#9]
Nice work with the plugin! Would be cool to see clearTimeout incorporated into it somehow - I use it quite a bit.

**Comment by avk** [comment]
Thanks! Any ideas on how `clearTimeout` and `clearInterval` could be improved? What are your main frustrations with them?

**Comment by mynameistechno** [comment]
They actually work fine, I was just thinking that you might want to
incorporate them into the plugin for the sake of consistency; just add some
more syntactic sugar around clearTimeout and clearInterval. That way I'm not
using the plugin for only half of my "timeout" needs, since I would still be
calling the native clear functions.

Maybe a $.cancel(timer)? What do you think? I can't think of anyway to
actually enhance the functionality ...

Best,
Mark

**Comment by avk** [comment]
Thanks for the idea but I'm just not sure adding another name for `clearTimeout` and `clearInterval` adds much value right now, especially at the cost of adding to the global jQuery namespace. If there's a bigger improvement to make, then I'll happily reconsider.
